DROP TABLE IF EXISTS COLOR_BAND;

CREATE TABLE COLOR_BAND (
  ID INT AUTO_INCREMENT  PRIMARY KEY,
  COLOR VARCHAR(255) UNIQUE NOT NULL,
  VALUE INTEGER NOT NULL
);

DROP TABLE IF EXISTS MULTIPLIER;

CREATE TABLE MULTIPLIER (
  ID INT AUTO_INCREMENT  PRIMARY KEY,
  COLOR VARCHAR(255) UNIQUE NOT NULL,
  VALUE FLOAT NOT NULL
);

DROP TABLE IF EXISTS TOLERANCE;

CREATE TABLE TOLERANCE (
  ID INT AUTO_INCREMENT  PRIMARY KEY,
  COLOR VARCHAR(255) UNIQUE NOT NULL,
  VALUE FLOAT NOT NULL
);